### ISSUE TITLE
Code release time

### ISSUE THREAD

**Issue by Penge666** [haoyu94/RoITr#1]
Studying your team's articles has greatly benefited me. However, there are still some questions that need to be further understood in conjunction with the code. May I ask when the code can be released for learning?

**Comment by haoyu94** [comment]
Hi, thanks for your interest in our work! Unfortunately, I am busy with the graduation stuff at this moment. But I believe an early version of the code will be released in June. Sorry for the inconvenience.

**Comment by Penge666** [comment]
> Hi, thanks for your interest in our work! Unfortunately, I am busy with the graduation stuff at this moment. But I believe an early version of the code will be released in June. Sorry for the inconvenience.

okay, thank you. Looking forward to it very much

**Comment by haoyu94** [comment]
The code has been released. Sorry for the inconvenience. As the code was re-structured and cleaned, it may contain some errors. If you have any problems in using it, just let me know.

**Comment by k794102577** [comment]
HEELO,Do you have any code to experiment with on modelnet40

**Comment by haoyu94** [comment]
Sorry we didn't include this experiment in our submission.
